
-- data cleaning
UPDATE customer_shooping
SET invoice_date = STR_TO_DATE(invoice_date, '%d-%m-%Y');

 UPDATE customer_shooping
SET 
    gender = TRIM(gender),
    category = TRIM(category),
    payment_method = TRIM(payment_method),
    shopping_mall = TRIM(shopping_mall),
    price = REPLACE(TRIM(price), ' ', ''),
    quantity = REPLACE(TRIM(quantity), ' ', '');
    
    

-- 1) Calculate the Total number of records
SELECT COUNT(*) AS total_records
FROM customer_shooping;


-- 2) Calculate the Count customers by gender
SELECT gender, COUNT(*) AS total
FROM customer_shooping
GROUP BY gender;


-- 3)Top 5 most purchased product categories
SELECT category,COUNT(*) AS total_purchase
from customer_shooping
group by category
order by total_purchase DESC
LIMIT 5;


-- 4) Calculate the Average age of customers
SELECT avg(age) As Customer_Age
from customer_shooping;

-- 5) Calculate the Total revenue generated
SELECT SUM(quantity * price) AS total_revenue
FROM customer_shooping;

-- 6) calcultae the most  payment method used
SELECT payment_method, COUNT(*) AS usage_count
FROM customer_shooping
GROUP BY payment_method
ORDER BY usage_count DESC;

-- 7) Which shopping mall generated the highest revenue
SELECT shopping_mall,SUM(quantity * price) AS mall_revenue
FROM customer_shooping
GROUP BY shopping_mall
ORDER BY mall_revenue DESC
LIMIT 1;

-- 8) calculte Category-wise revenue
SELECT category,
       SUM(quantity * price) AS revenue
FROM customer_shooping
GROUP BY category
ORDER BY revenue DESC;

-- 9) How many male vs. female customers are in the dataset
SELECT gender, COUNT(*) AS total_customers
FROM customer_shooping
GROUP BY gender;


-- 10) What are the total sales (revenue) generated by each product category.
SELECT category, SUM(quantity * price) AS total_revenue
FROM customer_shooping
GROUP BY category
ORDER BY total_revenue DESC;

-- 11) List each invoice with the customer’s gender and age.
SELECT s.invoice_no, c.customer_id, c.gender, c.age
FROM customer_shooping s
JOIN customer c
     ON s.customer_id = c.customer_id;
     
     
-- 12)Find customers who made purchases on the same date (self Join) 
SELECT 
    a.customer_id AS customer_1,
    b.customer_id AS customer_2,
    a.invoice_date
FROM customer_shooping a
JOIN customer_shooping b
    ON a.invoice_date = b.invoice_date
    AND a.customer_id <> b.customer_id;
    
    
-- 13)Show customer details with their purchases
SELECT s.invoice_no,s.customer_id,d.gender,d.age,s.category,s.price
FROM customer_shooping s
JOIN customer_shooping d
    ON s.customer_id = d.customer_id;
    
-- 14) Find customers who spent more than the average spending
SELECT * FROM customer_shooping
WHERE price > (SELECT AVG(price) FROM customer_shooping);


-- 15) Find customers older than the average customer age
SELECT AVG(age) FROM customer_shooping;


SELECT *FROM customer_shooping
WHERE age > (SELECT AVG(age) FROM customer_shooping);

-- 16) Find customers who bought more than the average quantity
SELECT avg(quantity) FROM customer_shooping;

Select  *FROM customer_shooping
where quantity > (SELECT avg(quantity) FROM customer_shooping);

-- 17) Find customers who placed orders on the earliest invoice date
SELECT MIN(invoice_date) FROM customer_shooping;

SELECT *FROM customer_shooping
WHERE invoice_date = (SELECT MIN(invoice_date)FROM customer_shooping);

-- 18) Calculte Average spending per customer
SELECT customer_id, AVG(price * quantity) AS avg_spending
FROM customer_shooping
GROUP BY customer_id
ORDER BY avg_spending DESC;

-- 19) Most purchased product category
SELECT category, COUNT(*) AS total_purchases
FROM customer_shooping
GROUP BY category
ORDER BY total_purchases DESC
LIMIT 1;



-- 20)How many total customers are in the dataset

SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM customer_shooping;

-- 21) Get all records where the customer is Female
SELECT *FROM customer_shooping
WHERE gender = 'Female';

-- 22) Get all customers who bought more than 3 items
SELECT *fROM customer_shooping
WHERE quantity > 3;

-- 23) Find records where customers paid using Credit Card
SELECT *FROM customer_shooping
WHERE payment_method = 'Credit Card';

-- 24)Find all purchases from the “Kanyon” shopping mall
SELECT *FROM customer_shooping
WHERE shopping_mall = 'Kanyon';


-- 25) Get all records where the price is greater than 1000
SELECT *FROM customer_shooping
WHERE price > 1000;

-- 26) Find customers between age 25 and 40
SELECT * FROM customer_shooping
WHERE age BETWEEN 25 AND 40;

-- 27) Get all male customers who bought “Clothing”
 
SELECT * FROM customer_shooping
WHERE gender = 'Male'AND category = 'Clothing';

-- 28) Get purchases made in the year 2022
SELECT *FROM customer_shooping
WHERE YEAR(STR_TO_DATE(invoice_date, '%d-%m-%Y')) = 2022;

-- 29) Get records where payment is not Cash
SELECT * FROM customer_shooping
WHERE payment_method <> 'Cash';

-- 30) Find all rows where category contains the word “Shoes”
SELECT *FROM customer_shooping
WHERE category LIKE '%Shoes%';


-- CASE STUDY

-- 31) Classify customers by age group
SELECT customer_id, age,
CASE
    WHEN age < 20 THEN 'Teen'
    WHEN age BETWEEN 20 AND 40 THEN 'Adult'
    WHEN age BETWEEN 41 AND 60 THEN 'Middle Age'
    ELSE 'Senior'
END AS age_group
FROM customer_shooping;

-- 32) Tag high-value purchases (price > 1000)
SELECT customer_id, category, price,
CASE
    WHEN price > 1000 THEN 'High Value'
    ELSE 'Regular'
END AS purchase_type
FROM customer_shooping;

-- 33 )Calculate rank of highest purchase amount

SELECT customer_id, price * quantity AS total_amount,
RANK() OVER (ORDER BY price * quantity DESC) AS purchase_rank
FROM customer_shooping;

-- 34) Average spending per customer

SELECT customer_id,
       SUM(price * quantity) AS total_spent,
       AVG(SUM(price * quantity)) OVER () AS avg_customer_spending
FROM customer_shooping
GROUP BY customer_id;

-- 35)Top Customers by Spending
SELECT
    customer_id,
    SUM(price) AS total_spent,
    NTILE(4) OVER (ORDER BY SUM(price) DESC) AS spending_quartile
FROM customer_shooping
GROUP BY customer_id
ORDER BY total_spent DESC;






















    







